#%RAML 1.0
title: My API with Types
mediaType: application/json
types:
  Org:
    type: object
    properties:
      onCall: Alertable
      Head: Manager
  Person:
    type: object
    properties:
      firstname: string
      lastname: string
      title?: string
      kind: string
  Phone:
    type: string
    pattern: "^[0-9|-]+$"
  Manager:
    type: Person
    properties:
      reports: Person[]
      phone:  Phone
  Admin:
    type: Person
    properties:
      clearanceLevel:
        enum: [ low, high ]
  AlertableAdmin:
    type: Admin
    properties:
      phone: Phone
  Alertable: Manager | AlertableAdmin
/{orgId}:
  uriParameters:
    orgId:
      type: string
  get:
    queryParameters:
      test: string
    responses:
      200:
        body:
          application/json:
            type: Org # reference to global type definition
            example:
              onCall:
                firstname: nico
                lastname: ark
                kind: admin
                clearanceLevel: low
                phone: "12321"
              Head:
                firstname: nico
                lastname: ark
                kind: manager
                reports:
                  -
                    firstname: nico
                    lastname: ark
                    kind: admin
                phone: "123-23"
