queryParameters:
  visibility:
    type: string
    required: false
    description: |
      The visibility of the property.
      The visibility of the new file. This parameter is only relevant when convert=false.

      Acceptable values are:
      - **"DEFAULT"**: The visibility of the new file is determined by the user's default visibility/sharing policies. (default)
      - **"PRIVATE"**: The new file will be visible to only the owner.

      The visibility of the new file. This parameter is only relevant when the source is not a native Google Doc and convert=false.

      Acceptable values are:
      - **DEFAULT"**: The visibility of the new file is determined by the user's default visibility/sharing policies. (default)
      - **"PRIVATE"**: The new file will be visible to only the owner.
