/**
 * DO NOT EDIT
 *
 * This file was automatically generated by
 *   https://github.com/Polymer/gen-typescript-declarations
 *
 * To modify these typings, edit the source file(s):
 *   api-console-styles.html
 */

/// <reference path="../polymer/types/polymer.d.ts" />
/// <reference path="../shadycss/apply-shim.d.ts" />
/// <reference path="../polymer/types/lib/elements/custom-style.d.ts" />

