/**
 * DO NOT EDIT
 *
 * This file was automatically generated by
 *   https://github.com/Polymer/gen-typescript-declarations
 *
 * To modify these typings, edit the source file(s):
 *   api-console.html
 */

/// <reference path="../polymer/types/polymer-element.d.ts" />
/// <reference path="../polymer/types/lib/utils/render-status.d.ts" />
/// <reference path="../raml-aware/raml-aware.d.ts" />
/// <reference path="../app-layout/app-drawer/app-drawer.d.ts" />
/// <reference path="../app-layout/app-drawer-layout/app-drawer-layout.d.ts" />
/// <reference path="../app-layout/app-header/app-header.d.ts" />
/// <reference path="../app-layout/app-header-layout/app-header-layout.d.ts" />
/// <reference path="../app-layout/app-scroll-effects/app-scroll-effects.d.ts" />
/// <reference path="../app-layout/app-toolbar/app-toolbar.d.ts" />
/// <reference path="../app-route/app-location.d.ts" />
/// <reference path="../app-route/app-route.d.ts" />
/// <reference path="../api-navigation/api-navigation.d.ts" />
/// <reference path="../api-documentation/api-documentation.d.ts" />
/// <reference path="../api-request-panel/api-request-panel.d.ts" />
/// <reference path="../paper-icon-button/paper-icon-button.d.ts" />
/// <reference path="../paper-toast/paper-toast.d.ts" />

declare namespace MulesoftApps {

  /**
   * # The API Console
   *
   * The API console for RAML (Restful Api Modeling Language) documents.
   * The RAML Console allows browsing of API documentation and in-browser testing of API methods.
   */
  class ApiConsole extends Polymer.Element {

    /**
     * `raml-aware` scope property to use.
     */
    aware: string|null|undefined;

    /**
     * Generated AMF json/ld model form the API spec.
     * The element assumes the object of the first array item to be a
     * type of `"http://raml.org/vocabularies/document#Document`
     * on AMF vocabulary.
     *
     * It is only usefult for the element to resolve references.
     */
    amfModel: object|any[]|null;
    _selectedShape: string|null|undefined;
    _selectedShapeType: string|null|undefined;

    /**
     * File location of the AMF json/ld model.
     * When changed it will download data from given location
     * and assign value to the `amfModel` property.
     *
     * ## Example
     * ```html
     * <api-console model-location="https://amf-parser/domain.com"></api-console>
     * ```
     */
    modelLocation: string|null|undefined;

    /**
     * Currently rendered page. It can be either `docs` or `request`.
     */
    page: string|null|undefined;

    /**
     * Computed value (read only), `true` when current page is the
     * request panel.
     */
    readonly isRequest: boolean|null|undefined;

    /**
     * Computed value (read only), `true` when current page is the
     * documentation panel.
     */
    readonly isDocs: boolean|null|undefined;

    /**
     * If not set or false then the install extension banner will be allowed to be shown.
     */
    noExtensionBanner: boolean|null|undefined;

    /**
     * When set the extension banner is rendered.
     */
    extensionBannerActive: boolean|null|undefined;

    /**
     * Forces the console to send headers defined in this string overriding any used defined
     * header.
     * It can be useful if the console has to send any recognizable string to a server without
     * user knowing about it.
     * The headers should be a HTTP headers string.
     */
    appendHeaders: string|null|undefined;

    /**
     * If true it will display a narrow layout.
     */
    narrow: boolean|null|undefined;

    /**
     * If set every request made from the console will be proxied by the service provided in this
     * value.
     * It will prefix entered URL with the proxy value. so the call to
     * `http://domain.com/path/?query=some+value` will become
     * `https://proxy.com/path/http://domain.com/path/?query=some+value`
     *
     * If the proxy require a to pass the URL as a query parameter define value as follows:
     * `https://proxy.com/path/?url=`. In this case be sure to set `proxy-encode-url`
     * attribute.
     */
    proxy: string|null|undefined;

    /**
     * If `proxy` is set, it will URL encode the request URL before appending it to the proxy URL.
     * `http://domain.com/path/?query=some+value` will become
     * `https://proxy.com/?url=http%3A%2F%2Fdomain.com%2Fpath%2F%3Fquery%3Dsome%2Bvalue`
     */
    proxyEncodeUrl: boolean|null|undefined;

    /**
     * If set then the API console hide the "try it" button from the
     * method documentation view. The request and response panels still will
     * be available, but to enter this section you'll have to do it
     * programatically.
     */
    noTryIt: boolean|null|undefined;

    /**
     * If set, the open navigation button will be always hidden.
     * The left hand side navigation will be hidden until `navigationOpened`
     * property is set.
     * The navigation will cover full screen, hiding the content.
     * This works best with `narrow` layout.
     */
    manualNavigation: boolean|null|undefined;

    /**
     * True when navigation is or should be opened.
     */
    navigationOpened: boolean|null|undefined;

    /**
     * Location of the `bower_components` folder.
     * It should be a path from server's root path including bower_components.
     */
    bowerLocation: string|null|undefined;

    /**
     * Hides the URL editor from the view.
     * Note that the editor is still in the DOM. This property just hiddes
     * it.
     */
    noUrlEditor: boolean|null|undefined;

    /**
     * A base URI for the API. To be set if RAML spec is missing `baseUri`
     * declaration and this produces invalid URL input. This information
     * is passed to the URL editor that prefixes the URL with `baseUri` value
     * if passed URL is a relative URL.
     */
    baseUri: string|null|undefined;

    /**
     * Removes the "Powered by Mulesoft" attribution from the main navigation.
     * The use of this feature must be in accordance with all licensing
     * and copyright protections required by the use of this software
     */
    noAttribution: boolean|null|undefined;

    /**
     * Computed value of AMF model of a type of `http://schema.org/WebAPI`
     */
    readonly webApi: object|null;

    /**
     * Computed title of the API
     */
    readonly apiTitle: string|null|undefined;

    /**
     * If true then current browser is Chrome.
     * Used to determine if the console should render the extension banner.
     */
    readonly isChrome: boolean|null|undefined;

    /**
     * An element that is a scroll target for the console.
     * By default it is the `window` object but if the lement is contained
     * in a containe that has overflow and height set then this should be
     * set to this container.
     */
    scrollTarget: object|null|undefined;
    ready(): void;
    connectedCallback(): void;
    disconnectedCallback(): void;
    _modelLocationChanged(url: any): void;
    _apiLoadEndHandler(xhr: any): void;
    _apiLoadErrorHandler(error: any): void;
    _onExtensionInstalled(): void;

    /**
     * Handler for the `tryit-requested` event. Sets current screen to
     * `request`.
     */
    _tryitHandler(): void;

    /**
     * Handler for the `amfModel` property change.
     * Sets the `path` to summary.
     */
    _amfModelChanged(): void;

    /**
     * Checks if property item has a type.
     *
     * @param model Model item.
     * @param type A type to lookup
     */
    _hasType(model: object|null, type: String|null): Boolean|null;

    /**
     * Gets a signle scalar value from a model.
     *
     * @param model Amf model to extract the value from.
     * @param key Model key to search for the value
     * @returns Value for key
     */
    _getValue(model: object|null, key: String|null): any|null;

    /**
     * Computes AMF's `http://schema.org/WebAPI` model
     *
     * @param amf AMF json/ld model for an API
     * @returns Web API declaration.
     */
    _computeWebApi(amf: any[]|object|null): object|null;

    /**
     * Computes value of `apiTitle` property.
     *
     * @param shape Shape of AMF model.
     * @returns Description if defined.
     */
    _computeApiTitle(shape: object|null): String|null|undefined;

    /**
     * Computes value for `isRequest` property.
     *
     * @param page Currently selected page.
     */
    _computeIsRequest(page: String|null): Boolean|null;

    /**
     * Computes value for `isDocs` property.
     *
     * @param page Currently selected page.
     */
    _computeIsDocs(page: String|null): Boolean|null;

    /**
     * Renders the extension banner if is Chrome and extension is not detected.
     */
    _initExtensionBanner(): void;

    /**
     * Dismisses Chrome extension banner.
     */
    dismissExtensionBanner(): void;

    /**
     * Handler for the navigation event dispatched by the `api-navigation`
     * component.
     * Normally it would set variables using Polymer's data binding. However,
     * because each change carries quite heavy task of computing the view
     * it feels more smooth to assign selection after the element is rendered
     * and not at the same time as the view is rendered.
     * It seems like foring more reflow events (the app renders empty element
     * first and then populate the view with data) but general look and feel
     * with this solution seems more smooth.
     * It is possible that this behavior will change in future release but for
     * now it is good enough. (Pawel)
     */
    _apiNavigationOcurred(e: CustomEvent|null): void;
  }
}

interface HTMLElementTagNameMap {
  "api-console": MulesoftApps.ApiConsole;
}
