#%RAML 1.0
version: 1.0
title: Product API
description: Product API

/product:
  description: Product
  get:
    description: |
      Retrieve all the Products.
  /{id}:
    description: Get Product by ID
    get:

/product/info:
  description: Get Product Info
  get:
