#%RAML 1.0
version: 1.0
title: Product API
description: Product API

/product:
  description: Product. http://getproduct
  get:
    description: |
      Retrieve all the Products. http://getproduct
  /{id}:
    description: Get Product by ID. http://getproductbyid
    get:

/product/info:
  description: Get Product Info. http://getproductinfo
  get:
