#%RAML 0.8
baseUri: https://localhost
title: Resource bodies

/bodies:
  put:
    body:
      multipart/form-data:
        formParameters:
          one:
            type: file
          two:
            type: string
            required: true
            example: blah
