#%RAML 1.0
baseUri: http://localhost
title: Resource bodies

types:
  userPicture:
    type: file
    fileTypes: ['image/jpeg', 'image/png']
    maxLength: 307200

  userName:
    type: string
    example: blah

  userProperties:
    properties:
      one:
        type: file
      two:
        type: string
        example: blah

/resource1:
  description: Form body with properties
  put:
    body:
      multipart/form-data:
        properties:
          one:
            type: file
          two:
            type: string
            required: true
            example: blah

/resource2:
  description: Form body with properties inheriting from root types
  put:
    body:
      multipart/form-data:
        properties:
          one:
            type: userPicture
          two:
            type: userName

/resource3:
  description: Form body with type inheriting from root type
  put:
    body:
      multipart/form-data:
        type: userProperties

/resource4:
  description: Form body with properties and type
  put:
    body:
      multipart/form-data:
        type: userProperties
        properties:
          three:
            type: string
