#%RAML 0.8
title: My API
baseUri: http://localhost

/resource:
  get:
    responses:
      200:
        body:
          application/json:
            example: |
              {
                "name": "John",
                "lastName": "Smith",
                "title": "Developer"
              }
