#%RAML 1.0 Library
# This file is located at libraries/file-type.raml

uses:
  another: ./another-types.raml

types:
  File:
    type: object
    properties:
      name:
      length:
        type: integer
      other: another.Thing
  Image:
    type: File
    properties:
      format: (Format | File)[]
  Format:
    type: object
    properties:
      type: string
  Schema: |
    {
      "type": "object",
      "properties": [
        {
          "name": "string"
        }
      ]
    }
