#%RAML 1.0 Library
# This file is located at libraries/person-schema.raml
schemas:
  Person: |
    {
      "type": "object",
      "properties": [
        {
          "name": "string"
        }
      ]
    }
