#%RAML 1.0
title: API body demo
version: v1
baseUri: http://{instance}.domain.com/

mediaType: [application/json, application/xml]
protocols: [HTTP, HTTPS]

description: |
  This is a description of demo API.

  This is **markdown**.

baseUriParameters:
  instance:
    description: |
      The execution environments. Can be one of:
      - development
      - staging
      - qa
      - production
    type: string
    enum: [development, staging, qa, production]
    pattern: (development|staging|qa|production)
    default: production
annotationTypes:
  deprecated: string
  annotationTest: nil
  clearanceLevel:
    properties:
      level:
        enum: [ low, medium, high ]
        required: true
      signature:
        pattern: "\\d{3}-\\w{12}"
        required: true
uses:
  ExampleType: resourceTypes/example-types.raml
types:
  Image: !include resourceTypes/image.raml
  Resource: !include resourceTypes/resource.raml
  AppPerson: !include resourceTypes/app-person.raml
  Product: !include resourceTypes/product.raml
  ErrorResource:
    description: A response that is errored
    type: object
    properties:
      error:
        type: boolean
        required: true
        example: true
        default: true
        description: Indicate that the response is errored.
      message:
        type: string
        description: The error message associated with the error.
        required: true
  Feature:
    description: A feature to test enum values in the URI parameters.
    type: string
    enum:
      - A
      - B
      - C
  Parent:
    type: object
    properties:
      id: number
      etag: string
  Child:
    type: Parent
    properties:
      name: string
  MultipartPerson:
    properties:
      name:
        type: string
        description: Name of the person
      email:
        type: string
      image:
        type: file
        fileTypes: ['image/jpeg', 'image/png']
      age:
        type: number
        description: Age of the person.
      optParam:
        type: number
        required: false
        description: Age of the person.
  QueryParam: !include types/query-string.raml
  OtherQueryParam: !include types/other-query-string.raml
resourceTypes:
  ResourceNotFound:
    get:
      responses:
        404:
          body:
            application/json:
              displayName: Not found response
              type: ErrorResource
            application/xml:
              displayName: Not found response
              type: !include schemas/error-response.xsd
              example: !include examples/e404.xml
  UnauthorizedResponse:
    get:
      responses:
        404:
          body:
            application/json:
              displayName: Unauthorized response
              type: ErrorResource
            application/xml:
              displayName: Unauthorized response
              type: !include schemas/error-response.xsd
              example: !include examples/e401.xml
  RequestErrorResponse:
    get:
      responses:
        400:
          description: The error response when one of the parameters is invalid and can't be parsed. Nothing can be done at the time except correcting the request to send valid data.
          body:
            application/json:
              displayName: Invalid request
              type: ErrorResource
            application/xml:
              displayName: Invalid request
              type: !include schemas/error-response.xsd
              example: !include examples/e400.xml
traits:
  Paginated: !include traits/pagination.raml
  Adminable: !include traits/adminable.raml
securitySchemes:
  oauth_2_0: !include securitySchemes/oauth_2_0.raml
  x-custom: !include securitySchemes/x-custom.raml
  basic: !include securitySchemes/basic.raml

documentation:
  - title: Test doc
    content: Test content

/people:
  displayName: People
  get:
    (annotationTest):
    displayName: List people
    description: Use this method to list all the people.
    is: [Paginated: {resourceType: AppPerson}]
    headers:
      x-people-op-id:
        (annotationTest):
        type: string
        pattern: ^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[4][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}$
        description: People ops ID. It is UUID v4 string
        example: 9719fa6f-c666-48e0-a191-290890760b30
  post:
    (deprecated): |
      This method is not deprecated. And this is only an annotation test.
    displayName: Create a person
    description: Use this method to add new person
    body:
      application/json:
        (deprecated): This response type is deprecated and soon will be replaced.
        type: AppPerson
      application/xml:
        type: !include schemas/person.xsd
        example: !include examples/person.xml
  put:
    displayName: Update a person
    description: Updates the person in the datastore.
    body:
      application/json:
        schema: !include schemas/person.json
        example: !include examples/person.json
      application/xml:
        type: !include schemas/person.xsd
        example: !include examples/person.xml
    responses:
      200:
        (deprecated): This response type is deprecated and soon will be replaced.
        description: |
          Success response for the body
        headers:
          X-Frame-Options:
            type: string
            examples:
              Deny: DENY
              SameOrigin: SAMEORIGIN
        body:
          application/json:
            schema: !include schemas/person.json
            example: !include examples/person.json
          application/xml:
            type: !include schemas/person.xsd
            example: !include examples/person.xml
      400:
        description: |
          Client error
        body:
          application/json:
            schema: !include schemas/error.json
            example: !include examples/error.json
          application/xml:
            type: !include schemas/error.xsd
            example: !include examples/error.xml
  /{personId}:
    securedBy: x-custom
    type: ResourceNotFound
    displayName: A person
    description: The endpoint to access information about the person
    uriParameters:
      personId:
        type: integer
        required: true
        description: The ID of the person in the system. It is generated by the database numeric value for the person.
        example: 1234
    get:
      displayName: Get a person
      description: Returns a person
      headers:
        x-client-id:
          (deprecated): This will be replaced
          example: 123456-acme.client.com
          description: The application id used to make a request. It can be obtained in the developer console.
          type: string
          required: true
        x-people-op-id:
          (annotationTest):
          type: string
          pattern: ^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[4][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}$
          description: People ops ID. It is UUID v4 string
          example: 9719fa6f-c666-48e0-a191-290890760b30
      responses:
        200:
          body:
            application/json:
              type: AppPerson
            application/xml:
              type: !include schemas/person.xsd
              example: !include examples/person.xml
    delete:
      displayName: Remove a person
      description: Removes the person from the datastore. This method do not returns any data in 200 response.
      responses:
        204:
      headers:
        x-people-op-id:
          (annotationTest):
          type: string
          pattern: ^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[4][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}$
          description: People ops ID. It is UUID v4 string
          example: 9719fa6f-c666-48e0-a191-290890760b30
    put:
      displayName: Update a person
      description: Updates the person in the datastore.
      queryParameters:
        testPatam: string
      body:
        application/json:
          type: AppPerson
        application/xml:
          type: !include schemas/person.xsd
          example: !include examples/person.xml
      responses:
        200:
      headers:
        x-people-op-id:
          (annotationTest):
          type: string
          pattern: ^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[4][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}$
          description: People ops ID. It is UUID v4 string
          example: 9719fa6f-c666-48e0-a191-290890760b30
/products:
  displayName: Products
  description: The API is to be used to access data about the products.
  post:
    displayName: Create product
    description: |
      Creates a product in the store.
      While creating a product the `id` and `etag` properties will be ignored.

      The endpoint will reject the request if exactly the same product is already defined in the
      datastore (all properties of both objects equals). Newly created product is available
      for listing but **it won't be available for ordering API** until it's availability is not set.
    body:
      application/json:
        type: Product
      application/xml:
        type: !include schemas/product.xsd
        example: !include examples/product.xml
    responses:
      200:
        body:
          application/json:
            type: Product
            examples:
              Product:
                id: d697f5cea85011e680f576304dec7eb7
                name: Super product
                quantity: 125
                unit: ml
                upc: "123456789101"
                available: true
                etag: "W/\"686897696a7c876b7e\""
              OtherProduct:
                id: 123e4567e89b12d3a456426655440000
                name: Acme Product
                quantity: 1
                unit: kg
                upc: "223456789101"
                available: true
                etag: "W/\"123456789\""
          application/xml:
            type: !include schemas/product.xsd
            example: !include examples/product.xml
      400:
        description: The request has been rejected. Probably the product already exists in the datastore.
/orgs:
  /{orgId}:
    get:
      displayName: Get organization
      description: Returns an organization info.
      responses:
        200:
          body:
            application/json:
              type: ExampleType.Org
              properties:
                id:
                  type: string
                  description: UUID generated ID
              example:
                id: "12345"
                onCall:
                  firstname: nico
                  lastname: ark
                  kind: AcmeAdmin
                  clearanceLevel: low
                  phone: "12321"
                Head:
                  firstname: nico
                  lastname: ark
                  kind: AcmeManager
                  reports:
                    -
                      firstname: nico
                      lastname: ark
                      kind: admin
                  phone: "123-23"
    put:
      body:
        application/json:
          type: ExampleType.Org
          properties:
            id:
              type: string
              description: UUID generated ID
      responses:
        200:
          body:
            application/json:
              type: ExampleType.Org
    /managers:
      get:
        responses:
          200:
            body:
              application/json:
                type: ExampleType.Manager[]
/messages:
  securedBy: [oauth_2_0]
  post:
    description: Create a new message
    is:  [Adminable]
    body:
      application/json:
        type: object
        properties:
          receiver:
            type: string
            description: receiver of the message
            required: true
          body:
            type: string
            description: A message body
            required: true
          important:
            type: boolean
            description: If true then the message will be marked as important
            default: false
            required: true
  get:
    description: |
      List user messages. It returns an array of messages for last of 7 days if
      `since` property is not set.
      You can use `since` and `until` query parameters to control messages time
      span.
    queryParameters:
      until:
        (annotationTest):
        type: date-only
        description: Date right limit of the messages query.
        example: 2017-05-12
      since:
        type: date-only
        description: Date left limit of the messages query.
        example: 2017-05-10
    responses:
      200:
        body:
          application/json:
            type: array
            items: !include resourceTypes/message-type.raml
            example: !include examples/messages-example.json
  /bulk:
    post:
      description: Bulk create messages.
      is:  [Adminable]
      body:
        application/json:
          (annotationTest):
          type: array
          items: !include resourceTypes/message-sent-type.raml
          examples:
            Example1: !include examples/messages-sent-example.json
/arrayBody:
  post:
    body:
      application/json:
        (deprecated): This response type is deprecated and soon will be replaced.
        description: |
          This demonstrates a body as an Array
        type: AppPerson[]
/multipart:
  post:
    body:
      multipart/form-data:
        type: MultipartPerson
/query-string-test:
  /node-type:
    get:
      queryString: QueryParam
  /union:
    get:
      queryString: QueryParam | OtherQueryParam
  /scalar:
    get:
      queryString:
        type: string
        example: test
  /array:
    get:
      queryString:
        type: OtherQueryParam[]
/query-parameters/{feature}:
  (deprecated): This endpoint is deprecated and will be removed.
  uriParameters:
    feature:
      type: string
      enum:
        - A
        - B
        - C
  get:
    (deprecated): This method is deprecated and will be removed.
    (clearanceLevel):
      level: high
      signature: 230-ghtwvfrs1itr
    description: To test enum values in the URI parameters for inline type declaration.
    queryParameters:
      testRepeatable:
        (deprecated): Test parameter will be removed in next version of the API.
        required: true
        type: string[]
        example: [value1, value2]
      numericRepeatable:
        required: true
        type: integer[]
        examples:
          Some-test-example: [123, 456]
          Other-example: [1011, 1213]
      notRequiredRepeatable:
        (annotationTest):
        type: array
        items: date-only
        required: false
  /{typeFeature}:
    (annotationTest):
    (deprecated): This method will be removed in future release of the API.
    uriParameters:
      typeFeature:
        (annotationTest):
        type: Feature
    get:
      (deprecated): This endpoint is deprecated and will be removed.
      description: To test enum values in the URI parameters for global type declaration.
