#%RAML 1.0
title: My API With Types
baseUri: http://google.com
types:
  Person:
    type: object
    discriminator: kind # refers to the `kind` property of object `Person`
    properties:
      kind: string # contains name of the kind of a `Person` instance
      name: string
  Employee: # kind may equal to `Employee; default value for `discriminatorValue`
    type: Person
    properties:
      employeeId: string
  User: # kind may equal to `User`; default value for `discriminatorValue`
    type: Person
    properties:
      userId: string

/testing:
  get:
    body:
      application/json:
        type: User
        example:
          userId: usser123
          name: nicolas
          kind: juan
/resourceEmployee:
  get:
    body:
      application/json:
        type: Employee
