#%RAML 1.0 DataType

type: object
properties:
  ID?: integer
  code: string
  price: number
  departureDate: string
  origin: string
  destination: string
  emptySeats: integer
  plane:
    type: object
    required: false
    properties:
      type: string
      totalSeats: integer
