#%RAML 0.8
title: "Groups and Nesting"
resourceTypes:
  - someType: {}
/non-resource-prefix/resource:
  get:
  /nested:
    get:
/non-resource-prefix/another-resource:
  get:
/resource-with-nesting:
  type: someType
  get:
  /nested:
    get:
  /another-nested:
    get:
/resource-without-methods-with-nesting:
  /nested:
    get:
  /another-nested:
    get:
