#%RAML 0.8
---
title: Example API
baseUri: #{test_api_uri}
traits:
  - secured:
      description: Some requests require authentication
  - unsecured:
      description: This is not secured
  - catpictures:
      description: requires cat headers
resourceTypes:
  - collection:
      description: bunk
/resource:
  displayName: First One
  get:
    description: get the first one
  is: [unsecured]
  /{resourceId}:
    uriParameters:
      resourceId:
        required: true
        description: Which resoure would you like to view
    get:
      queryParameters:
        filter:
          description: What to filter
          type: string
    post: !!null

/another/resource:
  displayName: Cats
  type: collection
  is: [secured, catpictures]
  get:
    queryParameters:
      chunk:
        displayName: page
        description: Which page to display
        type: integer
        example: 1
        minimum: 1
        maximum: 100
        required: true
      order:
        description: The sort order of resources
        type: string
        enum: ["oldest", "newest"]
        example: oldest
        minLength: 5
        maxLength: 7
        default: newest
      query:
        description: A query parameter
        repeat: true
  options: !!null
/resource-with-headers:
  displayName: Resource With headers
  get:
    headers:
      x-custom-header:
        displayName: Custom header
        description: This header is used to send data that...
        type: string
        pattern: /^\w+$/
