#%RAML 0.2
---
title: Example API
baseUri: #{test_api_uri}
traits:
  - secured:
      description: Some requests require authentication
  - unsecured:
      description: This is not secured
  - catpictures:
      description: requires cat headers
resourceTypes:
  - collection:
      description: bunk
/resource:
  displayName: First One
  get: !!null
  is: [unsecured]
  /{resourceId}:
    uriParameters:
      resourceId:
        required: true
    get: !!null
    post: !!null

/another/resource:
  displayName: Cats
  type: collection
  is: [secured, catpictures]
  get: !!null
  options: !!null
