#%RAML 1.0 DataType

properties: 
  featureName: 
    type: string
    required: false
    description: The name of the feature.
  featureRate: 
    type: number
    required: false
    description: The request limit rate for this feature, in queries per second.