#%RAML 1.0 DataType

properties: 
  source:
    type: string
    description: The imported file's content type to convert from.
    required: true
  targets:
    description: The possible content types to convert to.
    type: string[]
    required: true