#%RAML 1.0 DataType

type: object
description: The user's profile picture.
properties:
  url:
    type: string
    required: false
    description: A URL that points to a profile picture of this user.
