#%RAML 1.0 DataType

properties: 
  primaryRole: 
    type: string
    required: false
    description: A primary permission role.
  additionalRoles: 
    type: string[]
    required: false
    description: The supported additional roles with the primary role.