#%RAML 1.0 ResourceType
displayName: Standard request
get:
  queryParameters:
    access_token:
      type: string
      required: false
      description: |
        OAuth 2.0 token for the current user.

        One possible way to provide an OAuth 2.0 token.
    callback:
      type: string
      required: false
      description: |
        Name of the JavaScript callback function that handles the response.
        Used in JavaScript JSON-P requests.
    fields:
      type: string
      required: false
      description: |
        Selector specifying a subset of fields to include in the response.
        For more information, see the partial response section in the Performance Tips document.
        Use for better performance.
    key:
      type: string
      required: false
      description: |
        Required unless you provide an OAuth 2.0 token.
        Your API key identifies your project and provides you with API access, quota, and reports.
        Obtain your project's API key from the Google API Console.
    prettyPrint:
      type: boolean
      required: false
      description: |
        Returns response with indentations and line breaks.
        When this is false, it can reduce the response payload size, which might lead to better performance in some environments.
      default: true
    quotaUser:
      type: string
      required: false
      description: |
        Alternative to `userIp`.
        Lets you enforce per-user quotas from a server-side application even in cases when the user's IP address is unknown. This can occur, for example, with applications that run cron jobs on App Engine on a user's behalf.
        You can choose any arbitrary string that uniquely identifies a user, but it is limited to 40 characters.
        Overrides userIp if both are provided.
    userIp:
      type: string
      required: false
      description: |
        IP address of the end user for whom the API call is being made. Lets you enforce per-user quotas when calling the API from a server-side application.
