#%RAML 1.0 DataType

type: object
properties:
  type:
    type: string
    required: false
    description: The file type.
  size:
    type: string
    required: false
    description: The max upload size for this type.
